export {default as Allnotes} from './AllNotes/Allnotes'
export {default as ArchiveNotes} from './ArchiveNotes/ArchiveNotes'
export {default as TrashNotes} from './TrashNotes/TrashNotes'
export {default as TagNotes} from './TagNotes/TagNotes'
export {default as ErrorPage} from './ErrorPage/ErrorPage'